import Head from "next/head";

export default function TubeHead() {
  return (
    <Head>
      <title>trudy.tube</title>
      <meta name="description" content="Data noise generated by Trudy" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
